### ISSUE TITLE
Error in level 1 observations script

### ISSUE THREAD

**Issue by millerm12** [PEDSnet/Data-Quality-Analysis#15]
Encountered error in level 1 generate observations script:

"Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ", : Unable to retrieve JDBC result set for select CONCEPT_ID,CONCEPT_NAME from XXXX.CONCEPT where concept_class_id='DRG' and valid_end_date = '2007-09-30' and invalid_reason = 'D' (ORA-01861: literal does not match format string"

Works after changing valid_end_date = '2007-09-30' to valid_end_date = '30-SEP-07'

@writetoritu Should I make that change?

**Comment by writetoritu** [comment]
This is an Oracle/postgres issue . 
We should start reading concept_ids from a text file as opposed to queries for such cases.
