### ISSUE TITLE
Cross site comparison is validation

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/Data-Quality-Analysis#16]
Please update the DQ catalog

**Comment by millerm12** [comment]
The only cross-site comparison is CB-001, which is labelled correctly, I think we can close this issue

| check code | check type | function |
|---|---|---|
| CB-001  | unexpected fact to patient ratio| identifies irregular ratios of facts per patient as compared between sites |

**Comment by writetoritu** [comment]
CA-013 is cross-site too
