### ISSUE TITLE
implement AA-002 check for measurement_concept_id (labs)

### ISSUE THREAD

**Issue by eceowl** [PEDSnet/Data-Quality-Analysis#2]
<a href="https://github.com/writetoritu"><img src="https://avatars0.githubusercontent.com/u/8104269?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [writetoritu](https://github.com/writetoritu)**
_Wednesday Mar 15, 2017 at 18:15 GMT_

----

using the lab list provided in the conventions doc

**Comment by writetoritu** [comment]
maintain the list of lab concept ids in a text file.
