### ISSUE TITLE
clean up documentation and repo (based on Harris testing)

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/Data-Quality-Analysis#216]
-[ ] For level 1, I should be using v2, correct?
  - drop if exists in rxnorm tables

**Comment by ErezYehuda** [comment]
https://github.com/PEDSnet/Data-Quality-Analysis#required-downloads

Should include dplyr

**Comment by writetoritu** [comment]
add files in the data folder

**Comment by ErezYehuda** [comment]
Required downloads should include dplyr

**Comment by ErezYehuda** [comment]
Required downloads should include RPostgres (distinct from RPostgreSQL)

**Comment by writetoritu** [comment]
load plyr before dplyr

**Comment by writetoritu** [comment]
edit the list of files to included in previous data summary - top 50 drugs, and `total_fact_type_counts.csv`
