### ISSUE TITLE
create oracle views step should come after the rxnorm table creation

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/Data-Quality-Analysis#276]
documentation error

@janetzahner the step https://github.com/PEDSnet/Data-Quality-Analysis/blob/master/Doc/PEDSnet_DQA_Documentation.md#create-rxnorm-reference-tables should be performed before creation of oracle views. 

Sorry about this documentation error. copying @ErezYehuda

**Comment by janetzahner** [comment]
Thanks Ritu.  That fixed it.

Janet Zahner
Sr Database Administrator, Biomedical Informatics
Cincinnati Children's
3333 Burnet Avenue, MLC 1046, Cincinnati, OH 45229
Phone: 513.803.1946

Email: janet.zahner@cchmc.org<mailto:janet.zahner@cchmc.org>

[https://www.cincinnatichildrens.org/-/media/295b830c6eb94ee2b662c61a2945e5e6.ashx?h=67&w=200]<https://www.cincinnatichildrens.org/>

**Comment by ErezYehuda** [comment]
I've corrected the ordering of the relevant sections
