### ISSUE TITLE
Issues Connecting - Oracle Site

### ISSUE THREAD

**Issue by tuckerjs** [PEDSnet/Data-Quality-Analysis#306]
This is probably just a dumb error on my end, but after source("Run_DQA.R"), I get the following error

Error in .oci.Connect(.oci.drv(), username = username, password = password,  : 
  ORA-01017: invalid username/password; logon denied

I've checked to make sure the username and password in the config file in the Resources folder is correct. As mentioned, this is an Oracle site and this seems to be an error related to something Oracle.

**Comment by writetoritu** [comment]
@callahanc5 @ErezYehuda could one of you please help?

**Comment by callahanc5** [comment]
Could you also make sure that the Argos config file under your .argos directory has the correct login information? Also please double check that the driver is listed as Oracle in both files and that the related schemas are named correctly.

If those don't work, please also try making sure you can connect to the database directly and that the information used to connect is identical to what is in the config file.

**Comment by tuckerjs** [comment]
Was the argos config file having the wrong password. Runs fine now. Thanks.
