### ISSUE TITLE
bug with observation script (Oracle)

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/Data-Quality-Analysis#42]
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ", : Unable to retrieve JDBC result set for select CONCEPT_ID,CONCEPT_NAME from *****.CONCEPT where concept_class_id='DRG' and valid_end_date = '2007-09-30' and 
                                   invalid_reason = 'D' (ORA-01861: literal does not match format string
)

**Comment by writetoritu** [comment]
@tuckerjs have you executed observation scripts for your CDRN and did you encounter this bug?

**Comment by tuckerjs** [comment]
Yes, we do encounter this exact bug on our CDRN as well
