### ISSUE TITLE
several errors on oracle site 

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/Data-Quality-Analysis#43]
- [x]  Failed to generate condition occurrence report, see dqa.log for more details. : Error in if (grepl("future", message[3])) {: argument is of length zero

INFO [2017-03-23 14:24:11] Failed to generate observation report, see dqa.log for more details. : Error: cannot allocate vector of size 90.6 Mb

INFO [2017-03-23 14:35:53] Failed to generate measurement report, see dqa.log for more details. : Error: cannot allocate vector of size 208.9 Mb

INFO [2017-03-23 14:43:49] Failed to generate drug exposure report, see dqa.log for more details. : Error: cannot allocate vector of size 149.5 Mb

INFO [2017-03-23 14:44:23] Failed to generate visit payer report, see dqa.log for more details. : Error: cannot allocate vector of size 66.7 Mb

- [x] Failed to generate ADT occurrence report, see dqa.log for more details. : Error in if (!is.element(value, permissible_values) && !is.na(value)) return_message <- paste(return_message, : missing value where TRUE/FALSE needed

**Comment by millerm12** [comment]
@writetoritu We had the same "Error in if (grepl("future", message[3])) {: argument is of length zero"  in our device table when the start_date column was all NULL. We commented that out and it worked fine.

**Comment by writetoritu** [comment]
thanks @millerm12 looks like we need to add error handling in the device as well as adt_occurrence script.
