### ISSUE TITLE
Error on Level 2 Scripts

### ISSUE THREAD

**Issue by eceowl** [PEDSnet/Data-Quality-Analysis#5]
<a href="https://github.com/tuckerjs"><img src="https://avatars1.githubusercontent.com/u/22620458?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tuckerjs](https://github.com/tuckerjs)**
_Thursday Mar 16, 2017 at 17:23 GMT_

----

Ran into the following errors while running Level 2 scripts on a site. Did not get an error on patient, visit, or observation.

INFO [2017-03-16 13:00:14] Failed to generate level 2 condition report, see dqa.log for more details. : Error in eval(expr, envir, enclos): object 'condition_concept_id' not found

INFO [2017-03-16 13:03:56] Failed to generate level 2 procedure report, see dqa.log for more details. : Error in eval(expr, envir, enclos): object 'procedure_concept_id' not found

INFO [2017-03-16 13:07:59] Failed to generate level 2 drug report, see dqa.log for more details. : Error in eval(expr, envir, enclos): object 'drug_concept_id' not found

INFO [2017-03-16 13:09:23] Failed to generate level 2 measurement report, see dqa.log for more details. : Error in eval(expr, envir, enclos): object 'measurement_concept_id' not found

INFO [2017-03-16 13:09:23] Failed to generate level 2 measurement organism report, see dqa.log for more details. : Error in eval(expr, envir, enclos): object 'organism_concept_id' not found

**Comment by writetoritu** [comment]
@tuckerjs is this issue still valid?

**Comment by tuckerjs** [comment]
Yes, still having this issue

**Comment by writetoritu** [comment]
Level 2 scripts in R are currently not meant for ORacle
