### ISSUE TITLE
Total Counts script needs to be added

### ISSUE THREAD

**Issue by eceowl** [PEDSnet/Data-Quality-Analysis#7]
<a href="https://github.com/millerm12"><img src="https://avatars1.githubusercontent.com/u/17654526?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [millerm12](https://github.com/millerm12)**
_Friday Mar 17, 2017 at 17:05 GMT_

----

The script to generate the total_counts csv needs to be added to the Data folder. The script will also have to be modified to not be so specific to PEDSnet.

**Comment by writetoritu** [comment]
We already compute the count for each table in individual level 1 script and if we could somehow have that write to an output file that would be perfect instead of writing another R file
