### ISSUE TITLE
Error in condition_occurrence

### ISSUE THREAD

**Issue by tuckerjs** [PEDSnet/Data-Quality-Analysis#70]
INFO [2017-04-24 16:00:48] Failed to generate CONDITION_OCCURRENCE report, see dqa.log for more details. : Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ", : Unable to retrieve JDBC result set for select condition_status_source_value, count(*) as Freq from ****.condition_occurrence group by condition_status_source_value (ORA-00904: "CONDITION_STATUS_SOURCE_VALUE": invalid identifier
)

May be related to line 326 since none of the other stuff is abnormal code for checks.

    order_bins <-c(df_condition_type_concept_id$concept_id,NA)

**Comment by writetoritu** [comment]
@tuckerjs do you have the condition_status_source_value column in your CDRN yet, because we just added it for PEDSnet v2.5
this is a new column and if you dont have it it will give you an error
