### ISSUE TITLE
Error in Observation, Observation_source_value

### ISSUE THREAD

**Issue by tuckerjs** [PEDSnet/Data-Quality-Analysis#71]
INFO [2017-04-24 16:03:28] Failed to generate OBSERVATION report, see dqa.log for more details. : Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ", : Unable to retrieve JDBC result set for select observation_source_value, count(*) as count from ****.observation where observation_source_value is not null group by observation_source_value order by 2 desc limit 5 (ORA-00933: SQL command not properly ended
)

I would assume this is related to the "reportNullFlavors" function since nothing else looks out of place.

**Comment by writetoritu** [comment]
@tuckerjs Can you try running this command at your end 
`select observation_source_value, count(*) as count from ****.observation where observation_source_value is not null group by observation_source_value order by 2 desc limit 5`  and see if you are getting the same error?

**Comment by tuckerjs** [comment]
Yes I do and it's apparently due to the limit 5 part of that statement.

Oracle apparently doesn't have a limit function. There are two options for getting the same result as that query.

1. `select * from (select observation_source_value, count(*) as count from observation 
where observation_source_value is not null group by observation_source_value
order by 2 desc) where rownum <=5`

or 

2.`select observation_source_value, count(*) as count from observation 
where observation_source_value is not null group by observation_source_value
order by 2 desc fetch next 5 rows only`

**Comment by writetoritu** [comment]
This is the function that results into the error https://github.com/PEDSnet/Data-Quality-Analysis/blob/ac8199e97524f2cc10d4fc30f3e870aff2128d7c/Level1/library/PerformDatabaseOperations.R#L181 

I wonder what driver name are you supplying? is it `Oracle` or `ODBC`. If not then its defaulting to the postgres case.

**Comment by tuckerjs** [comment]
Driver is Oracle
