### ISSUE TITLE
Error in person, different number of rows

### ISSUE THREAD

**Issue by tuckerjs** [PEDSnet/Data-Quality-Analysis#72]
INFO [2017-04-24 16:06:39] Failed to generate PERSON report, see dqa.log for more details. : Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 1, 0

I think this is the error we get when a new check is added to the script, but not the DQA catalog. Did we add any additional checks to person script?

**Comment by writetoritu** [comment]
No we havent added any new check in the person table. Let me test at my end and get back.

**Comment by writetoritu** [comment]
@tuckerjs I am unable to reproduce it at my end (tried multiple cases). Did you pull the latest version of this repo before running the person script?

**Comment by tuckerjs** [comment]
@millerm12 ran the query on this so he may be able to give insight on that. I'm currently trying to rerun the queries using the newest scripts and will let you know.

**Comment by tuckerjs** [comment]
I received the same error after running the latest version.

**Comment by writetoritu** [comment]
ok cool, let me make that change and submit a PR.
