### ISSUE TITLE
DQA script order bins

### ISSUE THREAD

**Issue by eceowl** [PEDSnet/Data-Quality-Analysis#8]
<a href="https://github.com/millerm12"><img src="https://avatars1.githubusercontent.com/u/17654526?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [millerm12](https://github.com/millerm12)**
_Friday Mar 17, 2017 at 17:11 GMT_

----

There are a whole bunch of checks, primarily AA-002 checks, that strictly define accepted values. For example, there are only 8 acceptable values for observation_concept id manually written into the script. We may want to rewrite the order bins for these checks to make them less PEDSnet specific.

**Comment by writetoritu** [comment]
example https://github.com/PEDSnet/Data-Quality-Analysis/blob/master/Level1/PEDSnet%20CDM/v2/scripts/GenerateMeasurementReport_QueryWise.R#L413

**Comment by writetoritu** [comment]
- [ ]  Person
- [ ] Care site 
- [ ] Provider 
- [ ] Location 
- [ ] Visit occurrence 
- [ ]  visit payer 
- [ ]  adt occurrence 
- [ ] condition 
- [ ] procedure 
- [ ] drug exposure 
- [ ] measurement 
- [ ] observation 
- [ ] fact relationship 

@millerm12 we can keep track of the files being update on this comment
